### ISSUE TITLE
File view (desktop/mobile)

### ISSUE THREAD

**Issue by kurim** [pierobot/mangapie#183]
Move design discussion from https://github.com/pierobot/mangapie/issues/177 to this issue.

How it is:
![image](https://user-images.githubusercontent.com/1880220/81534362-3ac39700-9368-11ea-9662-0e5ec45e8ed2.png)

How it could be:
![image](https://user-images.githubusercontent.com/1880220/81534294-1667ba80-9368-11ea-8fbf-0e1739269684.png)

Desktop, FHD, Chromium

Mobile:
How it is:
![image](https://user-images.githubusercontent.com/1880220/81534495-6e062600-9368-11ea-8f63-c85728204248.png)

How it could be:
![image](https://user-images.githubusercontent.com/1880220/81534877-15835880-9369-11ea-9d86-3ff7f2186ced.png)

**Comment by donotos** [comment]
i believe that the preview link should not be just bellow the chapter link, after all we are on mobile view and the precision of the click with our finger is at best approximative.

**Comment by kurim** [comment]
I see your point.
how about this:
![image](https://user-images.githubusercontent.com/1880220/81585199-1b525b80-93b4-11ea-948f-886fbdef6a03.png)
(icon is a example not sure what to use for preview)

**Comment by donotos** [comment]
i think the icon is a good idea. it doesn't take much more space and do the work.

**Comment by kurim** [comment]
In this case we need some CSS tweaking...
"width:100%" > need to removed for mobile

like this:
```CSS
@media (max-width:576px){.col,.col-1,.col-10,.col-11,.col-12,.col-2,.col-3,.col-4,.col-5,.col-6,.col-7,.col-8,.col-9,.col-auto,.col-lg,.col-lg-1,.col-lg-10,.col-lg-11,.col-lg-12,.col-lg-2,.col-lg-3,.col-lg-4,.col-lg-5,.col-lg-6,.col-lg-7,.col-lg-8,.col-lg-9,.col-lg-auto,.col-md,.col-md-1,.col-md-10,.col-md-11,.col-md-12,.col-md-2,.col-md-3,.col-md-4,.col-md-5,.col-md-6,.col-md-7,.col-md-8,.col-md-9,.col-md-auto,.col-sm,.col-sm-1,.col-sm-10,.col-sm-11,.col-sm-12,.col-sm-2,.col-sm-3,.col-sm-4,.col-sm-5,.col-sm-6,.col-sm-7,.col-sm-8,.col-sm-9,.col-sm-auto,.col-xl,.col-xl-1,.col-xl-10,.col-xl-11,.col-xl-12,.col-xl-2,.col-xl-3,.col-xl-4,.col-xl-5,.col-xl-6,.col-xl-7,.col-xl-8,.col-xl-9,.col-xl-auto{position:relative;padding-right:15px;padding-left:15px}}
@media (min-width:577px){.col,.col-1,.col-10,.col-11,.col-12,.col-2,.col-3,.col-4,.col-5,.col-6,.col-7,.col-8,.col-9,.col-auto,.col-lg,.col-lg-1,.col-lg-10,.col-lg-11,.col-lg-12,.col-lg-2,.col-lg-3,.col-lg-4,.col-lg-5,.col-lg-6,.col-lg-7,.col-lg-8,.col-lg-9,.col-lg-auto,.col-md,.col-md-1,.col-md-10,.col-md-11,.col-md-12,.col-md-2,.col-md-3,.col-md-4,.col-md-5,.col-md-6,.col-md-7,.col-md-8,.col-md-9,.col-md-auto,.col-sm,.col-sm-1,.col-sm-10,.col-sm-11,.col-sm-12,.col-sm-2,.col-sm-3,.col-sm-4,.col-sm-5,.col-sm-6,.col-sm-7,.col-sm-8,.col-sm-9,.col-sm-auto,.col-xl,.col-xl-1,.col-xl-10,.col-xl-11,.col-xl-12,.col-xl-2,.col-xl-3,.col-xl-4,.col-xl-5,.col-xl-6,.col-xl-7,.col-xl-8,.col-xl-9,.col-xl-auto{position:relative;width:100%;padding-right:15px;padding-left:15px}}
```
Also we need modify the col-3
like this:
```CSS
.col-3 {
    flex: 0 0 25%;
    max-width: 25%;
    width: 25%
}
```
To force with of last read & add time

Result will be:
![image](https://user-images.githubusercontent.com/1880220/81735774-d868b480-9495-11ea-93b3-b6288540bc4a.png)
